import { Product } from './product.model';

export const PRODUCT_DATA: Product[] = [
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-1.jpg',
    name: 'book 1',
    price: '25',
    availability: 27,
    discount: 7,
    id: 3234344,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/Top-sellers/top-sellers-book/Book-2.jpg',
    name: 'book 2',
    price: '112',
    availability: 69,
    discount: 11,
    id: 75420458,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '3 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-3.jpg',
    name: 'book 3',
    price: '147',
    availability: 12,
    discount: 10,
    id: 8548274,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-4.jpg',
    name: 'book 4',
    price: '43',
    discount: 3,
    availability: 57,
    id: 32045215,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-5.jpg',
    name: 'book 5',
    price: '25',
    discount: 14,
    availability: 26,
    id: 854857,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-6.jpg',
    name: 'book 6',
    price: '85',
    discount: 7,
    availability: 12,
    id: 9654028,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-7.jpg',
    name: 'book 7',
    price: '39',
    discount: 4,
    availability: 9,
    id: 854877,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-8.jpg',
    name: 'book 8',
    price: '124',
    discount: 35,
    availability: 64,
    id: 5210425,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-9.jpg',
    name: 'book 9',
    price: '78',
    discount: 16,
    availability: 112,
    id: 854879,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-10.jpg',
    name: 'book 10',
    price: '35',
    discount: 2,
    availability: 327,
    id: 652407,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-11.jpg',
    name: 'book 11',
    price: '75',
    discount: 65,
    availability: 84,
    id: 8548578,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-12.jpg',
    name: 'book 12',
    price: '178',
    discount: 44,
    availability: 31,
    id: 985475,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-13.jpg',
    name: 'book 13',
    price: '157',
    discount: 12,
    availability: 27,
    id: 6524507,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-14.jpg',
    name: 'book 14',
    price: '112',
    discount: 30,
    availability: 69,
    id: 857489,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-15.jpg',
    name: 'book 15',
    price: '45',
    discount: 7,
    availability: 12,
    id: 658274,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-16.jpg',
    name: 'book 16',
    price: '32',
    discount: 10,
    availability: 57,
    id: 8544287,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-17.jpg',
    name: 'book 17',
    price: '12',
    discount: 20,
    availability: 26,
    id: 958427,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-18.jpg',
    name: 'book 18',
    price: '47',
    discount: 15,
    availability: 12,
    id: 8547284,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-19.jpg',
    name: 'book 19',
    price: '68',
    discount: 16,
    availability: 9,
    id: 19652407,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-20.jpg',
    name: 'book 20',
    price: '95',
    discount: 25,
    availability: 64,
    id: 9875045,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-21.jpg',
    name: 'book 21',
    price: '23',
    discount: 15,
    availability: 112,
    id: 96587,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/Top-sellers/top-sellers-book/Book 22.jpg',
    name: 'book 22',
    price: '28',
    discount: 35,
    availability: 327,
    id: 52487,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-23.jpg',
    name: 'book 23',
    price: '20',
    discount: 6,
    availability: 84,
    id: 6500845,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-book/book-24.jpg',
    name: 'book 24',
    price: '17',
    discount: 14,
    availability: 31,
    id: 3254270,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },

  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen1.jpg',
    name: 'Pen 1',
    price: '25',
    availability: 27,
    id: 584027,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen2.jpg',
    name: 'Pen 2',
    price: '112',
    availability: 69,
    id: 325047,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen3.jpg',
    name: 'Pen 3',
    price: '147',
    availability: 12,
    id: 950870,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen4.png',
    name: 'Pen 4',
    price: '43',
    availability: 57,
    id: 30254,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen5.jpg',
    name: 'Pen 5',
    price: '25',
    availability: 26,
    id: 855487,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen6.jpg',
    name: 'Pen 6',
    price: '85',
    availability: 12,
    id: 690542,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen7.jpg',
    name: 'Pen 7',
    price: '39',
    availability: 9,
    id: 86975849,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen8.jpg',
    name: 'Pen 8',
    price: '124',
    availability: 64,
    id: 654207,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen9.jpg',
    name: 'Pen 9',
    price: '78',
    availability: 112,
    id: 958704,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen10.jpg',
    name: 'Pen 10',
    price: '35',
    availability: 327,
    id: 250457,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/Pen-11.webp',
    name: 'Pen 11',
    price: '75',
    availability: 84,
    id: 652457,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen12.jpg',
    name: 'Pen 12',
    price: '178',
    availability: 31,
    id: 658579,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen13.jpg',
    name: 'Pen 13',
    price: '157',
    availability: 27,
    id: 525487,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen14.jpg',
    name: 'Pen 14',
    price: '112',
    availability: 69,
    id: 985784,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen15.jpg',
    name: 'Pen 15',
    price: '45',
    availability: 12,
    id: 654257,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen16.jpg',
    name: 'Pen 16',
    price: '32',
    availability: 57,
    id: 854975,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen17.jpg',
    name: 'Pen 17',
    price: '12',
    availability: 26,
    id: 998705,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen18.jpg',
    name: 'Pen 18',
    price: '47',
    availability: 12,
    id: 231524,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen19.jpg',
    name: 'Pen 19',
    price: '68',
    availability: 9,
    id: 985704,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-pen/pen20.jpg',
    name: 'Pen 20',
    price: '95',
    availability: 64,
    id: 98578,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },

  {
    image: '../../assets/Top-sellers/top-sellers-mobile/ihpne-12',
    name: 'Mobile 1',
    price: '925',
    availability: 27,
    id: 527540089,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone2.jpg',
    name: 'Mobile 2',
    price: '290',
    availability: 69,
    id: 964527,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone3.jpg',
    name: 'Mobile 3',
    price: '147',
    availability: 12,
    id: 645278,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone4.jpg',
    name: 'Mobile 4',
    price: '43',
    availability: 57,
    id: 132645,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone5.jpg',
    name: 'Mobile 5',
    price: '225',
    availability: 26,
    id: 8954642,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone6.jpg',
    name: 'Mobile 6',
    price: '85',
    availability: 12,
    id: 45874,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone7.jpg',
    name: 'Mobile 7',
    price: '539',
    availability: 9,
    id: 54261,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone8.jpg',
    name: 'Mobile 8',
    price: '124',
    availability: 64,
    id: 787545,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone9.jpg',
    name: 'Mobile 9',
    price: '378',
    availability: 112,
    id: 6345,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone10.jpg',
    name: 'Mobile 10',
    price: '335',
    availability: 327,
    id: 7845,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone11.jpg',
    name: 'Mobile 11',
    price: '75',
    availability: 84,
    id: 78745478,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone12.jpg',
    name: 'Mobile 12',
    price: '778',
    availability: 31,
    id: 785454,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone13.jpg',
    name: 'Mobile 13',
    price: '857',
    availability: 27,
    id: 5317,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone14.jpg',
    name: 'Mobile 14',
    price: '112',
    availability: 69,
    id: 45788,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone15.jpg',
    name: 'Mobile 15',
    price: '190',
    availability: 12,
    id: 7867824,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/Top-sellers/top-sellers-mobile/ihpne-12',
    name: 'Iphone',
    price: '900',
    availability: 57,
    id: 957845,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-mobile/phone17.jpg',
    name: 'phone17',
    price: '1175',
    availability: 26,
    id: 5642584,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },

  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv1.jpg',
    name: 'TV 1',
    price: '299',
    availability: 27,
    id: 85489,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv2.jpg',
    name: 'TV 2',
    price: '869',
    availability: 69,
    id: 642518,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv3.jpg',
    name: 'TV 3',
    price: '447',
    availability: 12,
    id: 643218,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv4.jpg',
    name: 'TV 4',
    price: '2100',
    availability: 57,
    id: 857984,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv5.jpg',
    name: 'TV 5',
    price: '909',
    availability: 26,
    id: 956548,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv6.jpg',
    name: 'TV 6',
    price: '1099',
    availability: 12,
    id: 785461,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv7.jpg',
    name: 'TV 7',
    price: '739',
    availability: 9,
    id: 497854,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv8.jpg',
    name: 'TV 8',
    price: '524',
    availability: 14,
    id: 875849,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv9.jpg',
    name: 'TV 9',
    price: '778',
    availability: 112,
    id: 96524,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv10.jpg',
    name: 'TV 10',
    price: '635',
    availability: 327,
    id: 978548,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv11.webp',
    name: 'TV 11',
    price: '475',
    availability: 84,
    id: 846519,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv12.jpg',
    name: 'TV 12',
    price: '378',
    availability: 31,
    id: 2154354,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/top-sellers-tv/tv13.jpg',
    name: 'TV 13',
    price: '557',
    availability: 27,
    id: 1234874,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },

  {
    image: '../../../assets/Top-sellers/Apple watch/1.webp',
    name: 'Apple watch 1',
    price: '326',
    availability: 405,
    id: 251684,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/2.webp',
    name: 'Apple watch 2',
    price: '699',
    availability: 61,
    id: 785485,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/3.webp',
    name: 'Apple watch 3',
    price: '1440',
    availability: 74,
    id: 24578,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/4.webp',
    name: 'Apple watch 4',
    price: '874',
    availability: 405,
    id: 4500487,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/5.webp',
    name: 'Apple watch 5',
    price: '765',
    availability: 61,
    id: 321504,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/6.webp',
    name: 'Apple watch 6',
    price: '1740',
    availability: 74,
    id: 8970548,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/7.webp',
    name: 'Apple watch 7',
    price: '210',
    availability: 405,
    id: 2001587,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/8.webp',
    name: 'Apple watch 8',
    price: '920',
    availability: 61,
    id: 625107,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/9.webp',
    name: 'Apple watch 9',
    price: '625',
    availability: 74,
    id: 6540075,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/10.webp',
    name: 'Apple watch 10',
    price: '784',
    availability: 405,
    id: 60589,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/11.jpg',
    name: 'Apple watch 11',
    price: '384',
    availability: 61,
    id: 30598408,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../../assets/Top-sellers/Apple watch/12.jpg',
    name: 'Apple watch 12',
    price: '740',
    availability: 74,
    id: 1001584,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
];
