export const BEST_SELLING_DATA = [
  {
    image: '../../../assets/Best-sellings/1/1.jpg',
    name: 'Coffe maker',
    availability: 123,
    id: 4512487,
    color: 'white',
    price: '235.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/2.jpg',
    name: 'Light',
    availability: 857,
    id: 780215,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/3.jpg',
    name: 'Bath pack',
    availability: 1857,
    id: 7785402,
    color: 'white',
    price: '5.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/4.jpg',
    name: 'Cloding',
    availability: 17,
    id: 33668,
    color: 'white',
    price: '50.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/5.jpg',
    name: 'Molfix',
    availability: 857,
    id: 9922508,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/6.jpg',
    name: 'Apple watch',
    availability: 857,
    id: 5836072,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/7.jpg',
    name: 'Mac keyboard',
    availability: 857,
    id: 70021548,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/8.jpg',
    name: 'Toy',
    availability: 857,
    id: 78409458,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/9.jpg',
    name: 'Molfix',
    availability: 857,
    id: 95215048,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/10.jpg',
    name: 'Molfix',
    availability: 857,
    id: 5421087,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
];
export const BestSellerParcel = [
  {
    image: '../../../assets/second-body-1.jpg',
    name: 'Molfix',
    availability: 857,
    id: 54872154,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
  },
  {
    image: '../../../assets/second-body-2.jpg',
    name: 'Showma',
    availability: 857,
    id: 865978458,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
  },
  {
    image: '../../../assets/second-body-3.jpg',
    name: 'Molfix',
    availability: 857,
    id: 232154857,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
  },
  {
    image: '../../../assets/second-body-4.jpg',
    name: 'Molfix',
    availability: 857,
    id: 3588902158,
    color: 'white',
    price: '2035.56',
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
  },
];
