export const BEST_SELLING_DATA = [
  {
    image: '../../../assets/Best-sellings/1/1.jpg',
    name: 'Coffe maker',
    availability: 123,
    id: 4512487,
    color: 'white',
    price: '259',
    discount: 13,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/2.jpg',
    name: 'Light',
    availability: 857,
    id: 780215,
    color: 'white',
    price: '49.90',
    discount: 5,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/3.jpg',
    name: 'Bath pack',
    availability: 1857,
    id: 7785402,
    color: 'white',
    price: '15.80',
    discount: 19,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/4.jpg',
    name: 'Cloding',
    availability: 17,
    id: 33668,
    color: 'white',
    price: '50.56',
    discount: 11,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/5.jpg',
    name: 'Molfix',
    availability: 857,
    id: 9922508,
    color: 'white',
    price: '29.90',
    discount: 7,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/6.jpg',
    name: 'Apple watch',
    availability: 857,
    id: 5836072,
    color: 'white',
    price: '295',
    discount: 3,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/7.jpg',
    name: 'Mac keyboard',
    availability: 857,
    id: 70021548,
    color: 'white',
    price: '129.90',
    discount: 15,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/8.jpg',
    name: 'Toy',
    availability: 857,
    id: 78409458,
    color: 'white',
    price: '90',
    discount: 19,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/9.jpg',
    name: 'Molfix',
    availability: 857,
    id: 95215048,
    color: 'white',
    price: '25.90',
    discount: 11,
    weight: '4.15',
    producedYear: '2019',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/Best-sellings/1/10.jpg',
    name: 'Molfix',
    availability: 857,
    id: 5421087,
    color: 'white',
    price: '95.90',
    weight: '4.15',
    producedYear: '2023',
    waranty: '1 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
];

export const BestSellerParcel = [
  {
    image: '../../../assets/second-body-1.jpg',
    name: 'Factory',
    availability: 21,
    id: 5483269847,
    color: 'green',
    price: '542.56',
    weight: '3.15',
    producedYear: '2015',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/second-body-2.jpg',
    name: 'Showma',
    availability: 123,
    id: 326815248,
    color: 'red',
    price: '45.56',
    weight: '1.15',
    producedYear: '2022',
    waranty: '1 year',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/second-body-3.jpg',
    name: 'Gold',
    availability: 123,
    id: 150796389,
    color: 'yellow',
    price: '5035.56',
    weight: '300.00g',
    producedYear: '2023',
    waranty: '30 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../assets/second-body-4.jpg',
    name: 'Coffe maker',
    availability: 123,
    id: 75925148,
    color: 'Blue',
    price: '135.56',
    weight: '4.15',
    producedYear: '2021',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
];

export const BestSellerClothes = [
  {
    image: '../../../assets/Best-sellings/shoes-1.jpg',
    name: 'Men gucci',
    availability: 21,
    id: 56119821546,
    color: 'black - gray',
    price: '49',
    discount: 9,
    weight: '715g',
    producedYear: '2022',
    waranty: '2 year',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../../assets/body-6.jpg',
    name: 'Shirt',
    availability: 65,
    id: 33008755199,
    color: 'black',
    price: '89',
    discount: 11,
    producedYear: '2015',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../../assets/body-11.jpg',
    name: 'Shirt',
    availability: 81,
    id: 7831542745,
    color: 'gray',
    price: '99',
    discount: 35,
    producedYear: '2015',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../../assets/body-12.jpg',
    name: 'Factory pot',
    availability: 21,
    id: 30986592154,
    color: 'green',
    price: '54.90',
    discount: 16,
    weight: '3.15',
    producedYear: '2015',
    waranty: '3 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../../assets/body-13.jpg',
    name: 'Camera',
    availability: 123,
    id: 6215417841,
    color: 'white',
    price: '95',
    discount: 10,
    weight: '700g',
    producedYear: '2022',
    waranty: '1 year',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../../assets/body-14.jpg',
    name: 'tickwat',
    availability: 123,
    id: 9565215487,
    color: '3 colors',
    price: '50',
    discount: 6,
    producedYear: '2023',
    waranty: '30 years',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
  {
    image: '../../../../assets/body-15.jpg',
    name: 'Black shirt',
    availability: 23,
    id: 562548754879,
    color: 'Blue',
    price: '135',
    producedYear: '2021',
    describtion:
      'Mini design: Mini GPS tracker, dimensions 47mm x 24mm x 18mm. Only one coin ♦♦♦ Wide use: The GPS tracker is designed for use anywhere Wallet wallet bags childrens bags important documents.But you can also use it in the car boat motor etc.and so on.You can use it anywhere. ♦♦♦ Built-in magnet: the live tracking functions are limitless.The mini GPS tracker has a strong magnet',
  },
];
