import { Gallery } from './gallery.model';

export const GALLERY_DATA: Gallery[] = [
  {
    image: '../../assets/gallery/gallery.jpg',
    name: ' 1',
    price: '25',
    availability: 27,
    id: 7873251405,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/gallery/gallery1.jpg',
    name: '2',
    price: '25',
    availability: 27,
    id: 9002005,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/gallery/galery2.jpg',
    name: '3',
    price: '25',
    availability: 27,
    id: 78451789585,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/gallery/gallery3.jpg',
    name: '4',
    price: '25',
    availability: 27,
    id: 975840021548,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/gallery/gallery4.gif',
    name: '5',
    price: '25',
    availability: 27,
    id: 54421876,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/gallery/gallery5.jpg',
    name: '6',
    price: '25',
    availability: 27,
    id: 6910548,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/gallery/galery6.jpg',
    name: '7',
    price: '25',
    availability: 27,
    id: 55210215899,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
  {
    image: '../../assets/gallery/gallery7.jpg',
    name: '8',
    price: '25',
    availability: 27,
    id: 5416308954,
    weight: '200g',
    color: 'red',
    producedYear: '2021',
    waranty: '2 years',
  },
];

export const GALLERY_DATA_PICTURE = [
  '../../assets/gallery/gallery.jpg',
  '../../../../assets/gallery/gallery-8.jpg',
  '../../assets/gallery/gallery-4.jpg',
  '../../assets/gallery/gallery-9.jpg',
  '../../assets/gallery/gallery3.jpg',
  '../../assets/gallery/gallery5.jpg',
  '../../assets/gallery/galery6.jpg',
  '../../assets/gallery/gallery7.jpg',
  '../../assets/gallery/gallery-8.jpg',
  '../../assets/gallery/gallery-10.jpg',
  '../../assets/gallery/gallery1.jpg',
  '../../assets/gallery/galery2.jpg',
];
